In [4]:
import pandas as pd
df = pd.read_csv('E:\\pocket_advocate\\bd_laws_english.csv')

In [5]:
df.head()

,Unnamed: 0.2,Unnamed: 0,Unnamed: 0.1,law_descripton,law_pass_date,law_subtitle,law_title,section_chapter_id,section_chapter_name,section_chapter_no,section_description,section_id,section_name,url_id,vol_ordinance,original_language,translated_language
0,0,0.0,0.0,NaN,"11th September, 1836",-,"The Districts Act, 1836",-,-,-,It shall be lawful for the,24127.0,Power to create new Districts,1.0,ACT NO. XXI OF 1836,en,en
1,1,1.0,1.0,-,"22nd March, 1850",-,"The Public Accountant's Default Act, 1850",-,-,-,"6. [Repealed by the Repealing Act, 1870 (Act N...",26414.0,[Repealed],2.0,ACT NO. XII OF 1850,en,en
2,2,2.0,2.0,-,"22nd March, 1850",-,"The Public Accountant's Default Act, 1850",-,-,-,1. Every public accountant shall give security...,1.0,Public Accountants to give security,2.0,ACT NO. XII OF 1850,en,en
3,3,3.0,3.0,-,"22nd March, 1850",-,"The Public Accountant's Default Act, 1850",-,-,-,2. In default of any Act having special refere...,2.0,"Amount and kind of security, and with what sur...",2.0,ACT NO. XII OF 1850,en,en
4,4,4.0,4.0,-,"22nd March, 1850",-,"The Public Accountant's Default Act, 1850",-,-,-,3. For the purposes of sections 1 and 2 of thi...,3.0,“Public accountant” defined,2.0,ACT NO. XII OF 1850,en,ca

In [6]:
df.describe()

       Unnamed: 0.2    Unnamed: 0  Unnamed: 0.1    section_id        url_id
count  38552.000000  38552.000000  38552.000000  38552.000000  38552.000000
mean   19275.500000  19275.500000  19275.500000  26102.040802    671.685023
std    11129.148126  11129.148126  11129.148126  14788.643077    414.333507
min        0.000000      0.000000      0.000000      1.000000      1.000000
25%     9637.750000   9637.750000   9637.750000  13731.750000    289.000000
50%    19275.500000  19275.500000  19275.500000  26320.500000    697.000000
75%    28913.250000  28913.250000  28913.250000  40574.250000   1032.000000
max    38551.000000  38551.000000  38551.000000  50455.000000   1378.000000

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 38552 entries, 0 to 38551
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0.2          38552 non-null  int64
 1   Unnamed: 0            38552 non-null  float64
 2   Unnamed: 0.1          38552 non-null  float64
 3   law_descripton        37696 non-null  str
 4   law_pass_date         38552 non-null  str
 5   law_subtitle          38552 non-null  str
 6   law_title             38552 non-null  str
 7   section_chapter_id    38552 non-null  str
 8   section_chapter_name  38552 non-null  str
 9   section_chapter_no    38552 non-null  str
 10  section_description   38482 non-null  str
 11  section_id            38552 non-null  float64
 12  section_name          37968 non-null  str
 13  url_id                38552 non-null  float64
 14  vol_ordinance         38007 non-null  str
 15  original_language     38552 non-null  str
 16  translated_language   36703 non-null  str
dtypes: float64(4), int64(1), str(12)
memory usage: 5.0 MB

In [8]:
df.shape

(38552, 17)

In [ ]:
df[:100]["law_descripton"].values

In [17]:
df[:100]["section_description"].values

<StringArray>
[                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      'It shall be lawful for the',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  '6. [Repealed by the Repealing Act, 1870 (Act No. XIV of 1870).]',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                '1. Every public accountant shall give security for the due discharge of the trusts of his office, and for the due account of all moneys which shall come into his possession or control, by reason of his office.',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            '2. In default of any Act having special reference to the office of any public accountant, the security given shall be of such amount and kind, real or personal, or both, and with such sureties (regard being had to the nature of the office), as shall be required by any rules made or to be made from time to time, by the authority by which each public accountant is appointed to his office.',
                                                                                                                                                                                                                                                                                                                                                                                                   '3. For the purposes of sections 1 and 2 of this Act, the expression “public accountant” means any person who as Official Assignee or Trustee, or as sarbarahkar, is entrusted with the receipt, custody or control of any moneys or securities for money, or the management of any lands belonging to any other person or persons; and for the purposes of sections 4 and 5 of this Act the expression shall also include any person who, by reason of any office held by him in the service of the State is entrusted with the receipt, custody or control of any moneys or securities for money, or the management of any lands belonging to the Government.',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              '4. The person or persons at the head of the office to which any public accountant belongs may proceed against any such public accountant and his securities for any loss or defalcation in his accounts, as if the amount thereof were an arrear of land-revenue due to Government.',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   '5. All Regulations and Acts now or hereafter to be in force for the recovery of arrears of land-revenue due to Government, and for recovery of damages by any person wrongfully proceeded against for any such arrear shall apply, with such changes in the forms of procedure as are necessary to make them applicable to the case, to the proceedings against and by such public accountant.',
                                                                                                                                                                                                                                                               '1. No Judge, Magistrate, Justice of the Peace, Collector or other person acting judicially shall be liable to be sued in any Civil Court for any act done or ordered to be done by him in the discharge of his judicial duty, whether or not within the limits of his jurisdiction: Provided that he at the time, in good faith, believed himself to have jurisdiction to do or order the act complained of; and no officer of any Court or other person, bound to execute the lawful warrants or orders of any such Judge, Magistrate, Justice of the Peace, Collector or other person acting judicially shall be liable to be sued in any Civil Court, for the execution of any warrant or order, which he would be bound to execute, if within the jurisdiction of the person issuing the same.',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    '9. All persons disobeying any lawful process issued as aforesaid for the purposes of the commission shall be liable to the same penalties as if the same had issued originally from the Court or other authority through whom it is executed.',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    '8. The commissioners shall have the same power of punishing contempt's and obstructions to their proceedings, as is given to Civil and Criminal Courts by the',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       '7. At any subsequent stage of the proceedings, the Government may, if it think fit, abandon the prosecution, and in such case may, if it think fit, on the application of the accuser, allow him to continue the prosecution, if he is desirous of so doing, on his furnishing such security as is hereinbefore mentioned.',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 '2. Whenever the Government shall be of opinion that there are good grounds for making a formal and public inquiry into the truth of any imputation of misbehaviour by any person',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              '4. When the Government shall think fit to conduct the prosecution, it shall nominate some person to conduct the same on its behalf.',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  '3. The inquiry may be committed either to the Court, Board or other authority to which the person accused is subordinate, or to any other person or persons, to be specially appointed by the Government, commissioners for the purpose: notice of which commission shall be given to the person accused ten days at least before the beginning of the inquiry.',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           '11. At the beginning of the inquiry the prosecutor shall exhibit the articles of charge to the commissioners, which shall be openly read, and the person accused shall thereupon be required to plead "guilty" or "not guilty" to each of them, which pleas shall be forthwith recorded with the articles of charge. If the person accused refuses, or without reasonable cause neglects, to appear to answer the charge either personally or by his counsel or agent, he shall be taken to admit the truth of the articles of charge.',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  '1. [Repealed by the Repealing Act, 1870 (Act No. XIV of 1870).]',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 '5. When the charge shall be brought by an accuser, the Government shall require the accusation to be reduced to writing, and verified by the oath or solemn affirmation of the accuser; and every person who shall wilfully and maliciously make any false accusation under this Act, upon such oath or affirmation, shall be liable to the penalties of perjury, but this enactment shall not be construed to prevent the Government from instituting any enquiry which it shall think fit, without such accusation on oath or solemn affirmation as aforesaid.',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          '12. The prosecutor shall then be entitled to address the commissioners in explanation of the articles of charge, and of the evidence by which they are to be proved: his address shall not be recorded.',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     '10. A copy of the articles of charge, and list of the documents and witnesses by which each charge is to be sustained, shall be delivered to the person accused, at least three days before the beginning of the inquiry, exclusive of the day of delivery and the first day of the inquiry.',

In [18]:
import pandas as pd
df_for = pd.read_csv('E:\\pocket_advocate\\bdlaws_formatted.csv')

In [21]:
df_for.head(100)

,Unnamed: 0,law_descripton,law_pass_date,law_subtitle,law_title,section_chapter_id,section_chapter_name,section_chapter_no,section_description,section_id,section_name,url_id,vol_ordinance
0,0,NaN,"11th September, 1836",NaN,"The Districts Act, 1836",NaN,NaN,NaN,It shall be lawful for the,24127,Power to create new Districts,1,ACT NO. XXI OF 1836
1,1,NaN,"22nd March, 1850",NaN,"The Public Accountant's Default Act, 1850",NaN,NaN,NaN,"6. [Repealed by the Repealing Act, 1870 (Act N...",26414,[Repealed],2,ACT NO. XII OF 1850
2,2,NaN,"22nd March, 1850",NaN,"The Public Accountant's Default Act, 1850",NaN,NaN,NaN,1. Every public accountant shall give security...,1,Public Accountants to give security,2,ACT NO. XII OF 1850
3,3,NaN,"22nd March, 1850",NaN,"The Public Accountant's Default Act, 1850",NaN,NaN,NaN,2. In default of any Act having special refere...,2,"Amount and kind of security, and with what sur...",2,ACT NO. XII OF 1850
4,4,NaN,"22nd March, 1850",NaN,"The Public Accountant's Default Act, 1850",NaN,NaN,NaN,3. For the purposes of sections 1 and 2 of thi...,3,“Public accountant” defined,2,ACT NO. XII OF 1850
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,NaN,"6th October, 1860",NaN,"The Penal Code, 1860",15.0,OF OFFENCES AFFECTING THE HUMAN BODY,Chapter XVI,331. Whoever voluntarily causes grievous hurt ...,3183,Voluntarily causing grievous hurt to extort co...,11,ACT NO. XLV OF 1860
96,96,NaN,"6th October, 1860",NaN,"The Penal Code, 1860",15.0,OF OFFENCES AFFECTING THE HUMAN BODY,Chapter XVI,332. Whoever voluntarily causes hurt to any pe...,3184,Voluntarily causing hurt to deter public serva...,11,ACT NO. XLV OF 1860
97,97,NaN,"6th October, 1860",NaN,"The Penal Code, 1860",15.0,OF OFFENCES AFFECTING THE HUMAN BODY,Chapter XVI,335. Whoever voluntarily causes grievous hurt ...,3187,Voluntarily causing grievous hurt on provocation,11,ACT NO. XLV OF 1860
98,98,NaN,"6th October, 1860",NaN,"The Penal Code, 1860",15.0,OF OFFENCES AFFECTING THE HUMAN BODY,Chapter XVI,334. Whoever voluntarily causes hurt on grave ...,3186,Voluntarily causing hurt on provocation,11,ACT NO. XLV OF 1860
99,99,NaN,"6th October, 1860",NaN,"The Penal Code, 1860",15.0,OF OFFENCES AFFECTING THE HUMAN BODY,Chapter XVI,336. Whoever does any act so rashly or neglige...,3188,Act endangering life or personal safety to others,11,ACT NO. XLV OF 1860

In [22]:
df_for.describe()

,Unnamed: 0,law_subtitle,section_chapter_id,section_id,url_id
count,38552.000000,0.0,16654.000000,38552.000000,38552.000000
mean,19275.500000,NaN,1016.629218,26102.040802,671.685023
std,11129.148126,NaN,683.185413,14788.643077,414.333507
min,0.000000,NaN,2.000000,1.000000,1.000000
25%,9637.750000,NaN,459.000000,13731.750000,289.000000
50%,19275.500000,NaN,898.000000,26320.500000,697.000000
75%,28913.250000,NaN,1714.000000,40574.250000,1032.000000
max,38551.000000,NaN,2285.000000,50455.000000,1378.000000

In [25]:
df_for.shape

(38552, 13)

In [26]:
df_for.info()

<class 'pandas.DataFrame'>
RangeIndex: 38552 entries, 0 to 38551
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0            38552 non-null  int64
 1   law_descripton        31815 non-null  str
 2   law_pass_date         37790 non-null  str
 3   law_subtitle          0 non-null      float64
 4   law_title             38552 non-null  str
 5   section_chapter_id    16654 non-null  float64
 6   section_chapter_name  17356 non-null  str
 7   section_chapter_no    16847 non-null  str
 8   section_description   38484 non-null  str
 9   section_id            38552 non-null  int64
 10  section_name          37055 non-null  str
 11  url_id                38552 non-null  int64
 12  vol_ordinance         38552 non-null  str
dtypes: float64(2), int64(3), str(8)
memory usage: 3.8 MB